name: local-nadeshiko
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.10
  - typer
  - rich
  - pip
  - fastapi
  - uvicorn
  - jinja2
  - python-dotenv
  - pytest
  - pip:
      - pysubs2
      - plexapi
      - pytest-ruff
      - ruff
