name: local-nadeshiko
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.10
  - typer
  - rich
  - pip
  - fastapi
  - uvicorn
  - jinja2
  - ruff
  - python-dotenv
  - pip:
      - pysubs2
      - plexapi
