name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
      with:
        persist-credentials: false

    - name: Set up Conda environment
      uses: conda-incubator/setup-miniconda@fc2d68f6413eb2d87b895e92f8584b5b94a10167 # v3
      with:
        activate-environment: hagi
        environment-file: environment-dev.yml
        auto-activate-base: false

    - name: Run tests and linting
      run: |
        PYTHONPATH=. conda run -n hagi pytest
